# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daemon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='daemon.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\004.;pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x64\x61\x65mon.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x13\n\x11SyncRoutesRequest2K\n\rDaemonService\x12:\n\nSyncRoutes\x12\x12.SyncRoutesRequest\x1a\x16.google.protobuf.Empty\"\x00\x42\x06Z\x04.;pbb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SYNCROUTESREQUEST = _descriptor.Descriptor(
  name='SyncRoutesRequest',
  full_name='SyncRoutesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['SyncRoutesRequest'] = _SYNCROUTESREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SyncRoutesRequest = _reflection.GeneratedProtocolMessageType('SyncRoutesRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYNCROUTESREQUEST,
  '__module__' : 'daemon_pb2'
  # @@protoc_insertion_point(class_scope:SyncRoutesRequest)
  })
_sym_db.RegisterMessage(SyncRoutesRequest)


DESCRIPTOR._options = None

_DAEMONSERVICE = _descriptor.ServiceDescriptor(
  name='DaemonService',
  full_name='DaemonService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=66,
  serialized_end=141,
  methods=[
  _descriptor.MethodDescriptor(
    name='SyncRoutes',
    full_name='DaemonService.SyncRoutes',
    index=0,
    containing_service=None,
    input_type=_SYNCROUTESREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DAEMONSERVICE)

DESCRIPTOR.services_by_name['DaemonService'] = _DAEMONSERVICE

# @@protoc_insertion_point(module_scope)
