FROM python:3.9.7-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
        libvirt-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements-dev.txt ./
RUN pip install -r requirements.txt -r requirements-dev.txt

COPY . .
ENTRYPOINT ["/usr/bin/env", "python3", "-m", "pytest"]
CMD ["tests"]
