from setuptools import setup

setup(
    name="restvirt",
    version="0.1",
    py_modules=[
        "dns_controller",
        "controller_pb2",
        "daemon_pb2_grpc",
        "version",
        "daemon",
        "host_pb2_grpc",
        "image",
        "port_forwarding",
        "port_forwarding_pb2",
        "dns_pb2_grpc",
        "route_pb2",
        "domain_pb2_grpc",
        "host_pb2",
        "domain_pb2",
        "controller_pb2_grpc",
        "models",
        "main",
        "dns_pb2",
        "network",
        "daemon_pb2",
        "controller",
        "route",
        "port_forwarding_pb2_grpc",
        "setup",
        "host",
        "volume_pb2_grpc",
        "route_pb2_grpc",
        "volume_pb2",
        "utils",
    ],
    url="",
    license="Apache",
    author="Ilya Verbitskiy",
    author_email="ilya@verbit.io",
    description="",
    entry_points={"console_scripts": ["restvirt=main:main"]},
    install_requires=[
        "libvirt-python==8.0.0",
        "grpcio==1.41.1",
        "grpcio-reflection==1.41.1",
        "protobuf==3.19.1",
        "pycdlib==1.12.0",
        "pyroute2==0.7.2",
        "nftables @ git+https://salsa.debian.org/pkg-netfilter-team/pkg-nftables.git@upstream/1.0.4#egg=nftables&subdirectory=py",
        "python-iptables==1.0.0",
        "SQLAlchemy==1.4.42",
        "xmltodict==0.12.0",
        "dnslib==0.9.16",
        "dnspython==2.2.1",
        "PyYAML==6.0",
    ],
)
