#!/bin/bash

rebar3 tar
make -C helper

read -s -p "remote sudo password: " SUDO_PASSWORD
echo

scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
echo -n "$SUDO_PASSWORD" | "$scriptDir/upgrade.escript" "$@"
