%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.8
%% Version source: file
-module(dns_pb).

-export([encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/3, merge_msgs/4]).
-export([verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).
-export([gpb_version_source/0]).


%% enumerated types

-export_type([]).

%% message types
-type dns_record_identifier() ::
      #{name                    => unicode:chardata(), % = 1, optional
        type                    => unicode:chardata() % = 2, optional
       }.

-type dns_record() ::
      #{name                    => unicode:chardata(), % = 1, optional
        type                    => unicode:chardata(), % = 2, optional
        ttl                     => non_neg_integer(), % = 3, optional, 64 bits
        records                 => [unicode:chardata()] % = 4, repeated
       }.

-type list_dns_records_request() ::
      #{
       }.

-type list_dns_records_response() ::
      #{dns_records             => [dns_record()]   % = 1, repeated
       }.

-type put_dns_record_request() ::
      #{dns_record              => dns_record()     % = 1, optional
       }.

-type empty() ::
      #{
       }.

-export_type(['dns_record_identifier'/0, 'dns_record'/0, 'list_dns_records_request'/0, 'list_dns_records_response'/0, 'put_dns_record_request'/0, 'empty'/0]).
-type '$msg_name'() :: dns_record_identifier | dns_record | list_dns_records_request | list_dns_records_response | put_dns_record_request | empty.
-type '$msg'() :: dns_record_identifier() | dns_record() | list_dns_records_request() | list_dns_records_response() | put_dns_record_request() | empty().
-export_type(['$msg_name'/0, '$msg'/0]).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/2}).
-endif.
-spec encode_msg('$msg'(), '$msg_name'()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/3}).
-endif.
-spec encode_msg('$msg'(), '$msg_name'(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
        true -> verify_msg(Msg, MsgName, Opts);
        false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        dns_record_identifier -> encode_msg_dns_record_identifier(id(Msg, TrUserData), TrUserData);
        dns_record -> encode_msg_dns_record(id(Msg, TrUserData), TrUserData);
        list_dns_records_request -> encode_msg_list_dns_records_request(id(Msg, TrUserData), TrUserData);
        list_dns_records_response -> encode_msg_list_dns_records_response(id(Msg, TrUserData), TrUserData);
        put_dns_record_request -> encode_msg_put_dns_record_request(id(Msg, TrUserData), TrUserData);
        empty -> encode_msg_empty(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_dns_record_identifier(Msg, TrUserData) -> encode_msg_dns_record_identifier(Msg, <<>>, TrUserData).


encode_msg_dns_record_identifier(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{name := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     case is_empty_string(TrF1) of
                         true -> Bin;
                         false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    case M of
        #{type := F2} ->
            begin
                TrF2 = id(F2, TrUserData),
                case is_empty_string(TrF2) of
                    true -> B1;
                    false -> e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
                end
            end;
        _ -> B1
    end.

encode_msg_dns_record(Msg, TrUserData) -> encode_msg_dns_record(Msg, <<>>, TrUserData).


encode_msg_dns_record(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{name := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     case is_empty_string(TrF1) of
                         true -> Bin;
                         false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    B2 = case M of
             #{type := F2} ->
                 begin
                     TrF2 = id(F2, TrUserData),
                     case is_empty_string(TrF2) of
                         true -> B1;
                         false -> e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
                     end
                 end;
             _ -> B1
         end,
    B3 = case M of
             #{ttl := F3} ->
                 begin
                     TrF3 = id(F3, TrUserData),
                     if TrF3 =:= 0 -> B2;
                        true -> e_varint(TrF3, <<B2/binary, 24>>, TrUserData)
                     end
                 end;
             _ -> B2
         end,
    case M of
        #{records := F4} ->
            TrF4 = id(F4, TrUserData),
            if TrF4 == [] -> B3;
               true -> e_field_dns_record_records(TrF4, B3, TrUserData)
            end;
        _ -> B3
    end.

encode_msg_list_dns_records_request(_Msg, _TrUserData) -> <<>>.

encode_msg_list_dns_records_response(Msg, TrUserData) -> encode_msg_list_dns_records_response(Msg, <<>>, TrUserData).


encode_msg_list_dns_records_response(#{} = M, Bin, TrUserData) ->
    case M of
        #{dns_records := F1} ->
            TrF1 = id(F1, TrUserData),
            if TrF1 == [] -> Bin;
               true -> e_field_list_dns_records_response_dns_records(TrF1, Bin, TrUserData)
            end;
        _ -> Bin
    end.

encode_msg_put_dns_record_request(Msg, TrUserData) -> encode_msg_put_dns_record_request(Msg, <<>>, TrUserData).


encode_msg_put_dns_record_request(#{} = M, Bin, TrUserData) ->
    case M of
        #{dns_record := F1} ->
            begin
                TrF1 = id(F1, TrUserData),
                if TrF1 =:= undefined -> Bin;
                   true -> e_mfield_put_dns_record_request_dns_record(TrF1, <<Bin/binary, 10>>, TrUserData)
                end
            end;
        _ -> Bin
    end.

encode_msg_empty(_Msg, _TrUserData) -> <<>>.

e_field_dns_record_records([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 34>>,
    Bin3 = e_type_string(id(Elem, TrUserData), Bin2, TrUserData),
    e_field_dns_record_records(Rest, Bin3, TrUserData);
e_field_dns_record_records([], Bin, _TrUserData) -> Bin.

e_mfield_list_dns_records_response_dns_records(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_dns_record(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_list_dns_records_response_dns_records([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 10>>,
    Bin3 = e_mfield_list_dns_records_response_dns_records(id(Elem, TrUserData), Bin2, TrUserData),
    e_field_list_dns_records_response_dns_records(Rest, Bin3, TrUserData);
e_field_list_dns_records_response_dns_records([], Bin, _TrUserData) -> Bin.

e_mfield_put_dns_record_request_dns_record(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_dns_record(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_unknown_elems/2}).
e_unknown_elems([Elem | Rest], Bin) ->
    BinR = case Elem of
               {varint, FNum, N} ->
                   BinF = e_varint(FNum bsl 3, Bin),
                   e_varint(N, BinF);
               {length_delimited, FNum, Data} ->
                   BinF = e_varint(FNum bsl 3 bor 2, Bin),
                   BinL = e_varint(byte_size(Data), BinF),
                   <<BinL/binary, Data/binary>>;
               {group, FNum, GroupFields} ->
                   Bin1 = e_varint(FNum bsl 3 bor 3, Bin),
                   Bin2 = e_unknown_elems(GroupFields, Bin1),
                   e_varint(FNum bsl 3 bor 4, Bin2);
               {fixed32, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 5, Bin),
                   <<BinF/binary, V:32/little>>;
               {fixed64, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 1, Bin),
                   <<BinF/binary, V:64/little>>
           end,
    e_unknown_elems(Rest, BinR);
e_unknown_elems([], Bin) -> Bin.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).

is_empty_string("") -> true;
is_empty_string(<<>>) -> true;
is_empty_string(L) when is_list(L) -> not string_has_chars(L);
is_empty_string(B) when is_binary(B) -> false.

string_has_chars([C | _]) when is_integer(C) -> true;
string_has_chars([H | T]) ->
    case string_has_chars(H) of
        true -> true;
        false -> string_has_chars(T)
    end;
string_has_chars(B) when is_binary(B), byte_size(B) =/= 0 -> true;
string_has_chars(C) when is_integer(C) -> true;
string_has_chars(<<>>) -> false;
string_has_chars([]) -> false.


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason:StackTrace ->
            erlang:raise(error, Reason, StackTrace);
        Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason ->
            erlang:raise(error, Reason,
                         erlang:get_stacktrace());
        Class:Reason ->
            StackTrace = erlang:get_stacktrace(),
            error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit(dns_record_identifier, Bin, TrUserData) -> id(decode_msg_dns_record_identifier(Bin, TrUserData), TrUserData);
decode_msg_2_doit(dns_record, Bin, TrUserData) -> id(decode_msg_dns_record(Bin, TrUserData), TrUserData);
decode_msg_2_doit(list_dns_records_request, Bin, TrUserData) -> id(decode_msg_list_dns_records_request(Bin, TrUserData), TrUserData);
decode_msg_2_doit(list_dns_records_response, Bin, TrUserData) -> id(decode_msg_list_dns_records_response(Bin, TrUserData), TrUserData);
decode_msg_2_doit(put_dns_record_request, Bin, TrUserData) -> id(decode_msg_put_dns_record_request(Bin, TrUserData), TrUserData);
decode_msg_2_doit(empty, Bin, TrUserData) -> id(decode_msg_empty(Bin, TrUserData), TrUserData).



decode_msg_dns_record_identifier(Bin, TrUserData) -> dfp_read_field_def_dns_record_identifier(Bin, 0, 0, 0, id(<<>>, TrUserData), id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_dns_record_identifier(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_dns_record_identifier_name(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_dns_record_identifier(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_dns_record_identifier_type(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_dns_record_identifier(<<>>, 0, 0, _, F@_1, F@_2, _) -> #{name => F@_1, type => F@_2};
dfp_read_field_def_dns_record_identifier(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dg_read_field_def_dns_record_identifier(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

dg_read_field_def_dns_record_identifier(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 -> dg_read_field_def_dns_record_identifier(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
dg_read_field_def_dns_record_identifier(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_dns_record_identifier_name(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        18 -> d_field_dns_record_identifier_type(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_dns_record_identifier(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                1 -> skip_64_dns_record_identifier(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                2 -> skip_length_delimited_dns_record_identifier(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                3 -> skip_group_dns_record_identifier(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                5 -> skip_32_dns_record_identifier(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
            end
    end;
dg_read_field_def_dns_record_identifier(<<>>, 0, 0, _, F@_1, F@_2, _) -> #{name => F@_1, type => F@_2}.

d_field_dns_record_identifier_name(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_dns_record_identifier_name(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_dns_record_identifier_name(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_dns_record_identifier(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

d_field_dns_record_identifier_type(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_dns_record_identifier_type(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_dns_record_identifier_type(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_dns_record_identifier(RestF, 0, 0, F, F@_1, NewFValue, TrUserData).

skip_varint_dns_record_identifier(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> skip_varint_dns_record_identifier(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
skip_varint_dns_record_identifier(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_dns_record_identifier(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_length_delimited_dns_record_identifier(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> skip_length_delimited_dns_record_identifier(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
skip_length_delimited_dns_record_identifier(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_dns_record_identifier(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

skip_group_dns_record_identifier(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_dns_record_identifier(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

skip_32_dns_record_identifier(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_dns_record_identifier(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_64_dns_record_identifier(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_dns_record_identifier(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

decode_msg_dns_record(Bin, TrUserData) -> dfp_read_field_def_dns_record(Bin, 0, 0, 0, id(<<>>, TrUserData), id(<<>>, TrUserData), id(0, TrUserData), id([], TrUserData), TrUserData).

dfp_read_field_def_dns_record(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_dns_record_name(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_dns_record(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_dns_record_type(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_dns_record(<<24, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_dns_record_ttl(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_dns_record(<<34, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_dns_record_records(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_dns_record(<<>>, 0, 0, _, F@_1, F@_2, F@_3, R1, TrUserData) -> #{name => F@_1, type => F@_2, ttl => F@_3, records => lists_reverse(R1, TrUserData)};
dfp_read_field_def_dns_record(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dg_read_field_def_dns_record(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

dg_read_field_def_dns_record(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 32 - 7 -> dg_read_field_def_dns_record(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dg_read_field_def_dns_record(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_dns_record_name(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        18 -> d_field_dns_record_type(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        24 -> d_field_dns_record_ttl(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        34 -> d_field_dns_record_records(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_dns_record(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                1 -> skip_64_dns_record(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                2 -> skip_length_delimited_dns_record(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                3 -> skip_group_dns_record(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                5 -> skip_32_dns_record(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData)
            end
    end;
dg_read_field_def_dns_record(<<>>, 0, 0, _, F@_1, F@_2, F@_3, R1, TrUserData) -> #{name => F@_1, type => F@_2, ttl => F@_3, records => lists_reverse(R1, TrUserData)}.

d_field_dns_record_name(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_dns_record_name(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_dns_record_name(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_dns_record(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, TrUserData).

d_field_dns_record_type(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_dns_record_type(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_dns_record_type(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_dns_record(RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, TrUserData).

d_field_dns_record_ttl(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_dns_record_ttl(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_dns_record_ttl(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 18446744073709551615, TrUserData), Rest},
    dfp_read_field_def_dns_record(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, TrUserData).

d_field_dns_record_records(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_dns_record_records(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_dns_record_records(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_dns_record(RestF, 0, 0, F, F@_1, F@_2, F@_3, cons(NewFValue, Prev, TrUserData), TrUserData).

skip_varint_dns_record(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> skip_varint_dns_record(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
skip_varint_dns_record(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_dns_record(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_length_delimited_dns_record(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> skip_length_delimited_dns_record(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
skip_length_delimited_dns_record(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_dns_record(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_group_dns_record(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_dns_record(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_32_dns_record(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_dns_record(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_64_dns_record(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_dns_record(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

decode_msg_list_dns_records_request(Bin, TrUserData) -> dfp_read_field_def_list_dns_records_request(Bin, 0, 0, 0, TrUserData).

dfp_read_field_def_list_dns_records_request(<<>>, 0, 0, _, _) -> #{};
dfp_read_field_def_list_dns_records_request(Other, Z1, Z2, F, TrUserData) -> dg_read_field_def_list_dns_records_request(Other, Z1, Z2, F, TrUserData).

dg_read_field_def_list_dns_records_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 32 - 7 -> dg_read_field_def_list_dns_records_request(Rest, N + 7, X bsl N + Acc, F, TrUserData);
dg_read_field_def_list_dns_records_request(<<0:1, X:7, Rest/binary>>, N, Acc, _, TrUserData) ->
    Key = X bsl N + Acc,
    case Key band 7 of
        0 -> skip_varint_list_dns_records_request(Rest, 0, 0, Key bsr 3, TrUserData);
        1 -> skip_64_list_dns_records_request(Rest, 0, 0, Key bsr 3, TrUserData);
        2 -> skip_length_delimited_list_dns_records_request(Rest, 0, 0, Key bsr 3, TrUserData);
        3 -> skip_group_list_dns_records_request(Rest, 0, 0, Key bsr 3, TrUserData);
        5 -> skip_32_list_dns_records_request(Rest, 0, 0, Key bsr 3, TrUserData)
    end;
dg_read_field_def_list_dns_records_request(<<>>, 0, 0, _, _) -> #{}.

skip_varint_list_dns_records_request(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> skip_varint_list_dns_records_request(Rest, Z1, Z2, F, TrUserData);
skip_varint_list_dns_records_request(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_list_dns_records_request(Rest, Z1, Z2, F, TrUserData).

skip_length_delimited_list_dns_records_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 57 -> skip_length_delimited_list_dns_records_request(Rest, N + 7, X bsl N + Acc, F, TrUserData);
skip_length_delimited_list_dns_records_request(<<0:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_list_dns_records_request(Rest2, 0, 0, F, TrUserData).

skip_group_list_dns_records_request(Bin, _, Z2, FNum, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_list_dns_records_request(Rest, 0, Z2, FNum, TrUserData).

skip_32_list_dns_records_request(<<_:32, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_list_dns_records_request(Rest, Z1, Z2, F, TrUserData).

skip_64_list_dns_records_request(<<_:64, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_list_dns_records_request(Rest, Z1, Z2, F, TrUserData).

decode_msg_list_dns_records_response(Bin, TrUserData) -> dfp_read_field_def_list_dns_records_response(Bin, 0, 0, 0, id([], TrUserData), TrUserData).

dfp_read_field_def_list_dns_records_response(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_list_dns_records_response_dns_records(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_list_dns_records_response(<<>>, 0, 0, _, R1, TrUserData) ->
    S1 = #{},
    if R1 == '$undef' -> S1;
       true -> S1#{dns_records => lists_reverse(R1, TrUserData)}
    end;
dfp_read_field_def_list_dns_records_response(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_list_dns_records_response(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_list_dns_records_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_list_dns_records_response(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_list_dns_records_response(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_list_dns_records_response_dns_records(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_list_dns_records_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_list_dns_records_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_list_dns_records_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_list_dns_records_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_list_dns_records_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_list_dns_records_response(<<>>, 0, 0, _, R1, TrUserData) ->
    S1 = #{},
    if R1 == '$undef' -> S1;
       true -> S1#{dns_records => lists_reverse(R1, TrUserData)}
    end.

d_field_list_dns_records_response_dns_records(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_list_dns_records_response_dns_records(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_list_dns_records_response_dns_records(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_dns_record(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_list_dns_records_response(RestF, 0, 0, F, cons(NewFValue, Prev, TrUserData), TrUserData).

skip_varint_list_dns_records_response(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_list_dns_records_response(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_list_dns_records_response(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_list_dns_records_response(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_list_dns_records_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_list_dns_records_response(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_list_dns_records_response(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_list_dns_records_response(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_list_dns_records_response(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_list_dns_records_response(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_list_dns_records_response(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_list_dns_records_response(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_list_dns_records_response(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_list_dns_records_response(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_put_dns_record_request(Bin, TrUserData) -> dfp_read_field_def_put_dns_record_request(Bin, 0, 0, 0, id('$undef', TrUserData), TrUserData).

dfp_read_field_def_put_dns_record_request(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_put_dns_record_request_dns_record(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_put_dns_record_request(<<>>, 0, 0, _, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{dns_record => F@_1}
    end;
dfp_read_field_def_put_dns_record_request(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_put_dns_record_request(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_put_dns_record_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_put_dns_record_request(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_put_dns_record_request(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_put_dns_record_request_dns_record(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_put_dns_record_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_put_dns_record_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_put_dns_record_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_put_dns_record_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_put_dns_record_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_put_dns_record_request(<<>>, 0, 0, _, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{dns_record => F@_1}
    end.

d_field_put_dns_record_request_dns_record(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_put_dns_record_request_dns_record(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_put_dns_record_request_dns_record(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_dns_record(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_put_dns_record_request(RestF,
                                              0,
                                              0,
                                              F,
                                              if Prev == '$undef' -> NewFValue;
                                                 true -> merge_msg_dns_record(Prev, NewFValue, TrUserData)
                                              end,
                                              TrUserData).

skip_varint_put_dns_record_request(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_put_dns_record_request(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_put_dns_record_request(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_put_dns_record_request(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_put_dns_record_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_put_dns_record_request(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_put_dns_record_request(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_put_dns_record_request(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_put_dns_record_request(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_put_dns_record_request(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_put_dns_record_request(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_put_dns_record_request(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_put_dns_record_request(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_put_dns_record_request(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_empty(Bin, TrUserData) -> dfp_read_field_def_empty(Bin, 0, 0, 0, TrUserData).

dfp_read_field_def_empty(<<>>, 0, 0, _, _) -> #{};
dfp_read_field_def_empty(Other, Z1, Z2, F, TrUserData) -> dg_read_field_def_empty(Other, Z1, Z2, F, TrUserData).

dg_read_field_def_empty(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 32 - 7 -> dg_read_field_def_empty(Rest, N + 7, X bsl N + Acc, F, TrUserData);
dg_read_field_def_empty(<<0:1, X:7, Rest/binary>>, N, Acc, _, TrUserData) ->
    Key = X bsl N + Acc,
    case Key band 7 of
        0 -> skip_varint_empty(Rest, 0, 0, Key bsr 3, TrUserData);
        1 -> skip_64_empty(Rest, 0, 0, Key bsr 3, TrUserData);
        2 -> skip_length_delimited_empty(Rest, 0, 0, Key bsr 3, TrUserData);
        3 -> skip_group_empty(Rest, 0, 0, Key bsr 3, TrUserData);
        5 -> skip_32_empty(Rest, 0, 0, Key bsr 3, TrUserData)
    end;
dg_read_field_def_empty(<<>>, 0, 0, _, _) -> #{}.

skip_varint_empty(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> skip_varint_empty(Rest, Z1, Z2, F, TrUserData);
skip_varint_empty(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_empty(Rest, Z1, Z2, F, TrUserData).

skip_length_delimited_empty(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 57 -> skip_length_delimited_empty(Rest, N + 7, X bsl N + Acc, F, TrUserData);
skip_length_delimited_empty(<<0:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_empty(Rest2, 0, 0, F, TrUserData).

skip_group_empty(Bin, _, Z2, FNum, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_empty(Rest, 0, Z2, FNum, TrUserData).

skip_32_empty(<<_:32, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_empty(Rest, Z1, Z2, F, TrUserData).

skip_64_empty(<<_:64, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_empty(Rest, Z1, Z2, F, TrUserData).

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        dns_record_identifier -> merge_msg_dns_record_identifier(Prev, New, TrUserData);
        dns_record -> merge_msg_dns_record(Prev, New, TrUserData);
        list_dns_records_request -> merge_msg_list_dns_records_request(Prev, New, TrUserData);
        list_dns_records_response -> merge_msg_list_dns_records_response(Prev, New, TrUserData);
        put_dns_record_request -> merge_msg_put_dns_record_request(Prev, New, TrUserData);
        empty -> merge_msg_empty(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_dns_record_identifier/3}).
merge_msg_dns_record_identifier(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{name := NFname}} -> S1#{name => NFname};
             {#{name := PFname}, _} -> S1#{name => PFname};
             _ -> S1
         end,
    case {PMsg, NMsg} of
        {_, #{type := NFtype}} -> S2#{type => NFtype};
        {#{type := PFtype}, _} -> S2#{type => PFtype};
        _ -> S2
    end.

-compile({nowarn_unused_function,merge_msg_dns_record/3}).
merge_msg_dns_record(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{name := NFname}} -> S1#{name => NFname};
             {#{name := PFname}, _} -> S1#{name => PFname};
             _ -> S1
         end,
    S3 = case {PMsg, NMsg} of
             {_, #{type := NFtype}} -> S2#{type => NFtype};
             {#{type := PFtype}, _} -> S2#{type => PFtype};
             _ -> S2
         end,
    S4 = case {PMsg, NMsg} of
             {_, #{ttl := NFttl}} -> S3#{ttl => NFttl};
             {#{ttl := PFttl}, _} -> S3#{ttl => PFttl};
             _ -> S3
         end,
    case {PMsg, NMsg} of
        {#{records := PFrecords}, #{records := NFrecords}} -> S4#{records => 'erlang_++'(PFrecords, NFrecords, TrUserData)};
        {_, #{records := NFrecords}} -> S4#{records => NFrecords};
        {#{records := PFrecords}, _} -> S4#{records => PFrecords};
        {_, _} -> S4
    end.

-compile({nowarn_unused_function,merge_msg_list_dns_records_request/3}).
merge_msg_list_dns_records_request(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,merge_msg_list_dns_records_response/3}).
merge_msg_list_dns_records_response(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {#{dns_records := PFdns_records}, #{dns_records := NFdns_records}} -> S1#{dns_records => 'erlang_++'(PFdns_records, NFdns_records, TrUserData)};
        {_, #{dns_records := NFdns_records}} -> S1#{dns_records => NFdns_records};
        {#{dns_records := PFdns_records}, _} -> S1#{dns_records => PFdns_records};
        {_, _} -> S1
    end.

-compile({nowarn_unused_function,merge_msg_put_dns_record_request/3}).
merge_msg_put_dns_record_request(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {#{dns_record := PFdns_record}, #{dns_record := NFdns_record}} -> S1#{dns_record => merge_msg_dns_record(PFdns_record, NFdns_record, TrUserData)};
        {_, #{dns_record := NFdns_record}} -> S1#{dns_record => NFdns_record};
        {#{dns_record := PFdns_record}, _} -> S1#{dns_record => PFdns_record};
        {_, _} -> S1
    end.

-compile({nowarn_unused_function,merge_msg_empty/3}).
merge_msg_empty(_Prev, New, _TrUserData) -> New.


verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        dns_record_identifier -> v_msg_dns_record_identifier(Msg, [MsgName], TrUserData);
        dns_record -> v_msg_dns_record(Msg, [MsgName], TrUserData);
        list_dns_records_request -> v_msg_list_dns_records_request(Msg, [MsgName], TrUserData);
        list_dns_records_response -> v_msg_list_dns_records_response(Msg, [MsgName], TrUserData);
        put_dns_record_request -> v_msg_put_dns_record_request(Msg, [MsgName], TrUserData);
        empty -> v_msg_empty(Msg, [MsgName], TrUserData);
        _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_dns_record_identifier/3}).
-dialyzer({nowarn_function,v_msg_dns_record_identifier/3}).
v_msg_dns_record_identifier(#{} = M, Path, TrUserData) ->
    case M of
        #{name := F1} -> v_type_string(F1, [name | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{type := F2} -> v_type_string(F2, [type | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (name) -> ok;
                      (type) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_dns_record_identifier(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), dns_record_identifier}, M, Path);
v_msg_dns_record_identifier(X, Path, _TrUserData) -> mk_type_error({expected_msg, dns_record_identifier}, X, Path).

-compile({nowarn_unused_function,v_msg_dns_record/3}).
-dialyzer({nowarn_function,v_msg_dns_record/3}).
v_msg_dns_record(#{} = M, Path, TrUserData) ->
    case M of
        #{name := F1} -> v_type_string(F1, [name | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{type := F2} -> v_type_string(F2, [type | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{ttl := F3} -> v_type_uint64(F3, [ttl | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{records := F4} ->
            if is_list(F4) ->
                   _ = [v_type_string(Elem, [records | Path], TrUserData) || Elem <- F4],
                   ok;
               true -> mk_type_error({invalid_list_of, string}, F4, [records | Path])
            end;
        _ -> ok
    end,
    lists:foreach(fun (name) -> ok;
                      (type) -> ok;
                      (ttl) -> ok;
                      (records) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_dns_record(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), dns_record}, M, Path);
v_msg_dns_record(X, Path, _TrUserData) -> mk_type_error({expected_msg, dns_record}, X, Path).

-compile({nowarn_unused_function,v_msg_list_dns_records_request/3}).
-dialyzer({nowarn_function,v_msg_list_dns_records_request/3}).
v_msg_list_dns_records_request(#{} = M, Path, _) ->
    lists:foreach(fun (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path) end, maps:keys(M)),
    ok;
v_msg_list_dns_records_request(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), list_dns_records_request}, M, Path);
v_msg_list_dns_records_request(X, Path, _TrUserData) -> mk_type_error({expected_msg, list_dns_records_request}, X, Path).

-compile({nowarn_unused_function,v_msg_list_dns_records_response/3}).
-dialyzer({nowarn_function,v_msg_list_dns_records_response/3}).
v_msg_list_dns_records_response(#{} = M, Path, TrUserData) ->
    case M of
        #{dns_records := F1} ->
            if is_list(F1) ->
                   _ = [v_msg_dns_record(Elem, [dns_records | Path], TrUserData) || Elem <- F1],
                   ok;
               true -> mk_type_error({invalid_list_of, {msg, dns_record}}, F1, [dns_records | Path])
            end;
        _ -> ok
    end,
    lists:foreach(fun (dns_records) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_list_dns_records_response(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), list_dns_records_response}, M, Path);
v_msg_list_dns_records_response(X, Path, _TrUserData) -> mk_type_error({expected_msg, list_dns_records_response}, X, Path).

-compile({nowarn_unused_function,v_msg_put_dns_record_request/3}).
-dialyzer({nowarn_function,v_msg_put_dns_record_request/3}).
v_msg_put_dns_record_request(#{} = M, Path, TrUserData) ->
    case M of
        #{dns_record := F1} -> v_msg_dns_record(F1, [dns_record | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (dns_record) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_put_dns_record_request(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), put_dns_record_request}, M, Path);
v_msg_put_dns_record_request(X, Path, _TrUserData) -> mk_type_error({expected_msg, put_dns_record_request}, X, Path).

-compile({nowarn_unused_function,v_msg_empty/3}).
-dialyzer({nowarn_function,v_msg_empty/3}).
v_msg_empty(#{} = M, Path, _) ->
    lists:foreach(fun (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path) end, maps:keys(M)),
    ok;
v_msg_empty(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), empty}, M, Path);
v_msg_empty(X, Path, _TrUserData) -> mk_type_error({expected_msg, empty}, X, Path).

-compile({nowarn_unused_function,v_type_uint64/3}).
-dialyzer({nowarn_function,v_type_uint64/3}).
v_type_uint64(N, _Path, _TrUserData) when 0 =< N, N =< 18446744073709551615 -> ok;
v_type_uint64(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, uint64, unsigned, 64}, N, Path);
v_type_uint64(X, Path, _TrUserData) -> mk_type_error({bad_integer, uint64, unsigned, 64}, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
        B when is_binary(B) -> ok;
        {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
        error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) -> mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR)))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() ->
    [{{msg, dns_record_identifier}, [#{name => name, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []}, #{name => type, fnum => 2, rnum => 3, type => string, occurrence => optional, opts => []}]},
     {{msg, dns_record},
      [#{name => name, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []},
       #{name => type, fnum => 2, rnum => 3, type => string, occurrence => optional, opts => []},
       #{name => ttl, fnum => 3, rnum => 4, type => uint64, occurrence => optional, opts => []},
       #{name => records, fnum => 4, rnum => 5, type => string, occurrence => repeated, opts => []}]},
     {{msg, list_dns_records_request}, []},
     {{msg, list_dns_records_response}, [#{name => dns_records, fnum => 1, rnum => 2, type => {msg, dns_record}, occurrence => repeated, opts => []}]},
     {{msg, put_dns_record_request}, [#{name => dns_record, fnum => 1, rnum => 2, type => {msg, dns_record}, occurrence => optional, opts => []}]},
     {{msg, empty}, []}].


get_msg_names() -> [dns_record_identifier, dns_record, list_dns_records_request, list_dns_records_response, put_dns_record_request, empty].


get_group_names() -> [].


get_msg_or_group_names() -> [dns_record_identifier, dns_record, list_dns_records_request, list_dns_records_response, put_dns_record_request, empty].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
        Fs when is_list(Fs) -> Fs;
        error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) -> erlang:error({no_such_enum, EnumName}).


find_msg_def(dns_record_identifier) -> [#{name => name, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []}, #{name => type, fnum => 2, rnum => 3, type => string, occurrence => optional, opts => []}];
find_msg_def(dns_record) ->
    [#{name => name, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []},
     #{name => type, fnum => 2, rnum => 3, type => string, occurrence => optional, opts => []},
     #{name => ttl, fnum => 3, rnum => 4, type => uint64, occurrence => optional, opts => []},
     #{name => records, fnum => 4, rnum => 5, type => string, occurrence => repeated, opts => []}];
find_msg_def(list_dns_records_request) -> [];
find_msg_def(list_dns_records_response) -> [#{name => dns_records, fnum => 1, rnum => 2, type => {msg, dns_record}, occurrence => repeated, opts => []}];
find_msg_def(put_dns_record_request) -> [#{name => dns_record, fnum => 1, rnum => 2, type => {msg, dns_record}, occurrence => optional, opts => []}];
find_msg_def(empty) -> [];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) -> erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) -> erlang:error({no_enum_defs, E, V}).



get_service_names() -> ['DNS'].


get_service_def('DNS') ->
    {{service, 'DNS'},
     [#{name => 'GetDNSRecord', input => dns_record_identifier, output => dns_record, input_stream => false, output_stream => false, opts => []},
      #{name => 'ListDNSRecords', input => list_dns_records_request, output => list_dns_records_response, input_stream => false, output_stream => false, opts => []},
      #{name => 'PutDNSRecord', input => put_dns_record_request, output => dns_record, input_stream => false, output_stream => false, opts => []},
      #{name => 'DeleteDNSRecord', input => dns_record_identifier, output => empty, input_stream => false, output_stream => false, opts => []}]};
get_service_def(_) -> error.


get_rpc_names('DNS') -> ['GetDNSRecord', 'ListDNSRecords', 'PutDNSRecord', 'DeleteDNSRecord'];
get_rpc_names(_) -> error.


find_rpc_def('DNS', RpcName) -> find_rpc_def_DNS(RpcName);
find_rpc_def(_, _) -> error.


find_rpc_def_DNS('GetDNSRecord') -> #{name => 'GetDNSRecord', input => dns_record_identifier, output => dns_record, input_stream => false, output_stream => false, opts => []};
find_rpc_def_DNS('ListDNSRecords') -> #{name => 'ListDNSRecords', input => list_dns_records_request, output => list_dns_records_response, input_stream => false, output_stream => false, opts => []};
find_rpc_def_DNS('PutDNSRecord') -> #{name => 'PutDNSRecord', input => put_dns_record_request, output => dns_record, input_stream => false, output_stream => false, opts => []};
find_rpc_def_DNS('DeleteDNSRecord') -> #{name => 'DeleteDNSRecord', input => dns_record_identifier, output => empty, input_stream => false, output_stream => false, opts => []};
find_rpc_def_DNS(_) -> error.


fetch_rpc_def(ServiceName, RpcName) ->
    case find_rpc_def(ServiceName, RpcName) of
        Def when is_map(Def) -> Def;
        error -> erlang:error({no_such_rpc, ServiceName, RpcName})
    end.


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
fqbin_to_service_name(<<"DNS">>) -> 'DNS';
fqbin_to_service_name(X) -> error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
service_name_to_fqbin('DNS') -> <<"DNS">>;
service_name_to_fqbin(X) -> error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
fqbins_to_service_and_rpc_name(<<"DNS">>, <<"GetDNSRecord">>) -> {'DNS', 'GetDNSRecord'};
fqbins_to_service_and_rpc_name(<<"DNS">>, <<"ListDNSRecords">>) -> {'DNS', 'ListDNSRecords'};
fqbins_to_service_and_rpc_name(<<"DNS">>, <<"PutDNSRecord">>) -> {'DNS', 'PutDNSRecord'};
fqbins_to_service_and_rpc_name(<<"DNS">>, <<"DeleteDNSRecord">>) -> {'DNS', 'DeleteDNSRecord'};
fqbins_to_service_and_rpc_name(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
service_and_rpc_name_to_fqbins('DNS', 'GetDNSRecord') -> {<<"DNS">>, <<"GetDNSRecord">>};
service_and_rpc_name_to_fqbins('DNS', 'ListDNSRecords') -> {<<"DNS">>, <<"ListDNSRecords">>};
service_and_rpc_name_to_fqbins('DNS', 'PutDNSRecord') -> {<<"DNS">>, <<"PutDNSRecord">>};
service_and_rpc_name_to_fqbins('DNS', 'DeleteDNSRecord') -> {<<"DNS">>, <<"DeleteDNSRecord">>};
service_and_rpc_name_to_fqbins(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"DNSRecordIdentifier">>) -> dns_record_identifier;
fqbin_to_msg_name(<<"DNSRecord">>) -> dns_record;
fqbin_to_msg_name(<<"ListDNSRecordsRequest">>) -> list_dns_records_request;
fqbin_to_msg_name(<<"ListDNSRecordsResponse">>) -> list_dns_records_response;
fqbin_to_msg_name(<<"PutDNSRecordRequest">>) -> put_dns_record_request;
fqbin_to_msg_name(<<"google.protobuf.Empty">>) -> empty;
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin(dns_record_identifier) -> <<"DNSRecordIdentifier">>;
msg_name_to_fqbin(dns_record) -> <<"DNSRecord">>;
msg_name_to_fqbin(list_dns_records_request) -> <<"ListDNSRecordsRequest">>;
msg_name_to_fqbin(list_dns_records_response) -> <<"ListDNSRecordsResponse">>;
msg_name_to_fqbin(put_dns_record_request) -> <<"PutDNSRecordRequest">>;
msg_name_to_fqbin(empty) -> <<"google.protobuf.Empty">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec fqbin_to_enum_name(_) -> no_return().
fqbin_to_enum_name(E) -> error({gpb_error, {badenum, E}}).


-spec enum_name_to_fqbin(_) -> no_return().
enum_name_to_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_package_name() -> 'google.protobuf'.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> true.


source_basename() -> "dns.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() -> ["dns.proto", "empty.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["dns", "empty"].


get_msg_containment("dns") -> [dns_record, dns_record_identifier, list_dns_records_request, list_dns_records_response, put_dns_record_request];
get_msg_containment("empty") -> [empty];
get_msg_containment(P) -> error({gpb_error, {badproto, P}}).


get_pkg_containment("dns") -> undefined;
get_pkg_containment("empty") -> 'google.protobuf';
get_pkg_containment(P) -> error({gpb_error, {badproto, P}}).


get_service_containment("dns") -> ['DNS'];
get_service_containment("empty") -> [];
get_service_containment(P) -> error({gpb_error, {badproto, P}}).


get_rpc_containment("dns") -> [{'DNS', 'GetDNSRecord'}, {'DNS', 'ListDNSRecords'}, {'DNS', 'PutDNSRecord'}, {'DNS', 'DeleteDNSRecord'}];
get_rpc_containment("empty") -> [];
get_rpc_containment(P) -> error({gpb_error, {badproto, P}}).


get_enum_containment("dns") -> [];
get_enum_containment("empty") -> [];
get_enum_containment(P) -> error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"DNSRecordIdentifier">>) -> "dns";
get_proto_by_msg_name_as_fqbin(<<"PutDNSRecordRequest">>) -> "dns";
get_proto_by_msg_name_as_fqbin(<<"ListDNSRecordsRequest">>) -> "dns";
get_proto_by_msg_name_as_fqbin(<<"DNSRecord">>) -> "dns";
get_proto_by_msg_name_as_fqbin(<<"ListDNSRecordsResponse">>) -> "dns";
get_proto_by_msg_name_as_fqbin(<<"google.protobuf.Empty">>) -> "empty";
get_proto_by_msg_name_as_fqbin(E) -> error({gpb_error, {badmsg, E}}).


get_proto_by_service_name_as_fqbin(<<"DNS">>) -> "dns";
get_proto_by_service_name_as_fqbin(E) -> error({gpb_error, {badservice, E}}).


-spec get_proto_by_enum_name_as_fqbin(_) -> no_return().
get_proto_by_enum_name_as_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_protos_by_pkg_name_as_fqbin(<<"google.protobuf">>) -> ["empty"];
get_protos_by_pkg_name_as_fqbin(E) -> error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.19.8".

gpb_version_as_list() ->
    [4,19,8].

gpb_version_source() ->
    "file".
