%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.8
%% Version source: file
-module(host_pb).

-export([encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/3, merge_msgs/4]).
-export([verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).
-export([gpb_version_source/0]).


%% enumerated types

-export_type([]).

%% message types
-type create_bootstrap_token_request() ::
      #{expires_at              => unicode:chardata() % = 1, optional
       }.

-type create_bootstrap_token_response() ::
      #{token                   => unicode:chardata() % = 1, optional
       }.

-type host() ::
      #{name                    => unicode:chardata(), % = 1, optional
        address                 => unicode:chardata() % = 2, optional
       }.

-type list_hosts_request() ::
      #{
       }.

-type list_hosts_response() ::
      #{hosts                   => [host()]         % = 1, repeated
       }.

-type register_host_request() ::
      #{host                    => host(),          % = 1, optional
        token                   => unicode:chardata() % = 2, optional
       }.

-type heartbeat_request() ::
      #{host                    => host()           % = 1, optional
       }.

-type heartbeat_response() ::
      #{
       }.

-type empty() ::
      #{
       }.

-export_type(['create_bootstrap_token_request'/0, 'create_bootstrap_token_response'/0, 'host'/0, 'list_hosts_request'/0, 'list_hosts_response'/0, 'register_host_request'/0, 'heartbeat_request'/0, 'heartbeat_response'/0, 'empty'/0]).
-type '$msg_name'() :: create_bootstrap_token_request | create_bootstrap_token_response | host | list_hosts_request | list_hosts_response | register_host_request | heartbeat_request | heartbeat_response | empty.
-type '$msg'() :: create_bootstrap_token_request() | create_bootstrap_token_response() | host() | list_hosts_request() | list_hosts_response() | register_host_request() | heartbeat_request() | heartbeat_response() | empty().
-export_type(['$msg_name'/0, '$msg'/0]).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/2}).
-endif.
-spec encode_msg('$msg'(), '$msg_name'()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/3}).
-endif.
-spec encode_msg('$msg'(), '$msg_name'(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
        true -> verify_msg(Msg, MsgName, Opts);
        false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        create_bootstrap_token_request -> encode_msg_create_bootstrap_token_request(id(Msg, TrUserData), TrUserData);
        create_bootstrap_token_response -> encode_msg_create_bootstrap_token_response(id(Msg, TrUserData), TrUserData);
        host -> encode_msg_host(id(Msg, TrUserData), TrUserData);
        list_hosts_request -> encode_msg_list_hosts_request(id(Msg, TrUserData), TrUserData);
        list_hosts_response -> encode_msg_list_hosts_response(id(Msg, TrUserData), TrUserData);
        register_host_request -> encode_msg_register_host_request(id(Msg, TrUserData), TrUserData);
        heartbeat_request -> encode_msg_heartbeat_request(id(Msg, TrUserData), TrUserData);
        heartbeat_response -> encode_msg_heartbeat_response(id(Msg, TrUserData), TrUserData);
        empty -> encode_msg_empty(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_create_bootstrap_token_request(Msg, TrUserData) -> encode_msg_create_bootstrap_token_request(Msg, <<>>, TrUserData).


encode_msg_create_bootstrap_token_request(#{} = M, Bin, TrUserData) ->
    case M of
        #{expires_at := F1} ->
            begin
                TrF1 = id(F1, TrUserData),
                case is_empty_string(TrF1) of
                    true -> Bin;
                    false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                end
            end;
        _ -> Bin
    end.

encode_msg_create_bootstrap_token_response(Msg, TrUserData) -> encode_msg_create_bootstrap_token_response(Msg, <<>>, TrUserData).


encode_msg_create_bootstrap_token_response(#{} = M, Bin, TrUserData) ->
    case M of
        #{token := F1} ->
            begin
                TrF1 = id(F1, TrUserData),
                case is_empty_string(TrF1) of
                    true -> Bin;
                    false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                end
            end;
        _ -> Bin
    end.

encode_msg_host(Msg, TrUserData) -> encode_msg_host(Msg, <<>>, TrUserData).


encode_msg_host(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{name := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     case is_empty_string(TrF1) of
                         true -> Bin;
                         false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    case M of
        #{address := F2} ->
            begin
                TrF2 = id(F2, TrUserData),
                case is_empty_string(TrF2) of
                    true -> B1;
                    false -> e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
                end
            end;
        _ -> B1
    end.

encode_msg_list_hosts_request(_Msg, _TrUserData) -> <<>>.

encode_msg_list_hosts_response(Msg, TrUserData) -> encode_msg_list_hosts_response(Msg, <<>>, TrUserData).


encode_msg_list_hosts_response(#{} = M, Bin, TrUserData) ->
    case M of
        #{hosts := F1} ->
            TrF1 = id(F1, TrUserData),
            if TrF1 == [] -> Bin;
               true -> e_field_list_hosts_response_hosts(TrF1, Bin, TrUserData)
            end;
        _ -> Bin
    end.

encode_msg_register_host_request(Msg, TrUserData) -> encode_msg_register_host_request(Msg, <<>>, TrUserData).


encode_msg_register_host_request(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{host := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     if TrF1 =:= undefined -> Bin;
                        true -> e_mfield_register_host_request_host(TrF1, <<Bin/binary, 10>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    case M of
        #{token := F2} ->
            begin
                TrF2 = id(F2, TrUserData),
                case is_empty_string(TrF2) of
                    true -> B1;
                    false -> e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
                end
            end;
        _ -> B1
    end.

encode_msg_heartbeat_request(Msg, TrUserData) -> encode_msg_heartbeat_request(Msg, <<>>, TrUserData).


encode_msg_heartbeat_request(#{} = M, Bin, TrUserData) ->
    case M of
        #{host := F1} ->
            begin
                TrF1 = id(F1, TrUserData),
                if TrF1 =:= undefined -> Bin;
                   true -> e_mfield_heartbeat_request_host(TrF1, <<Bin/binary, 10>>, TrUserData)
                end
            end;
        _ -> Bin
    end.

encode_msg_heartbeat_response(_Msg, _TrUserData) -> <<>>.

encode_msg_empty(_Msg, _TrUserData) -> <<>>.

e_mfield_list_hosts_response_hosts(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_host(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_list_hosts_response_hosts([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 10>>,
    Bin3 = e_mfield_list_hosts_response_hosts(id(Elem, TrUserData), Bin2, TrUserData),
    e_field_list_hosts_response_hosts(Rest, Bin3, TrUserData);
e_field_list_hosts_response_hosts([], Bin, _TrUserData) -> Bin.

e_mfield_register_host_request_host(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_host(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_mfield_heartbeat_request_host(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_host(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_unknown_elems/2}).
e_unknown_elems([Elem | Rest], Bin) ->
    BinR = case Elem of
               {varint, FNum, N} ->
                   BinF = e_varint(FNum bsl 3, Bin),
                   e_varint(N, BinF);
               {length_delimited, FNum, Data} ->
                   BinF = e_varint(FNum bsl 3 bor 2, Bin),
                   BinL = e_varint(byte_size(Data), BinF),
                   <<BinL/binary, Data/binary>>;
               {group, FNum, GroupFields} ->
                   Bin1 = e_varint(FNum bsl 3 bor 3, Bin),
                   Bin2 = e_unknown_elems(GroupFields, Bin1),
                   e_varint(FNum bsl 3 bor 4, Bin2);
               {fixed32, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 5, Bin),
                   <<BinF/binary, V:32/little>>;
               {fixed64, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 1, Bin),
                   <<BinF/binary, V:64/little>>
           end,
    e_unknown_elems(Rest, BinR);
e_unknown_elems([], Bin) -> Bin.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).

is_empty_string("") -> true;
is_empty_string(<<>>) -> true;
is_empty_string(L) when is_list(L) -> not string_has_chars(L);
is_empty_string(B) when is_binary(B) -> false.

string_has_chars([C | _]) when is_integer(C) -> true;
string_has_chars([H | T]) ->
    case string_has_chars(H) of
        true -> true;
        false -> string_has_chars(T)
    end;
string_has_chars(B) when is_binary(B), byte_size(B) =/= 0 -> true;
string_has_chars(C) when is_integer(C) -> true;
string_has_chars(<<>>) -> false;
string_has_chars([]) -> false.


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason:StackTrace ->
            erlang:raise(error, Reason, StackTrace);
        Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason ->
            erlang:raise(error, Reason,
                         erlang:get_stacktrace());
        Class:Reason ->
            StackTrace = erlang:get_stacktrace(),
            error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit(create_bootstrap_token_request, Bin, TrUserData) -> id(decode_msg_create_bootstrap_token_request(Bin, TrUserData), TrUserData);
decode_msg_2_doit(create_bootstrap_token_response, Bin, TrUserData) -> id(decode_msg_create_bootstrap_token_response(Bin, TrUserData), TrUserData);
decode_msg_2_doit(host, Bin, TrUserData) -> id(decode_msg_host(Bin, TrUserData), TrUserData);
decode_msg_2_doit(list_hosts_request, Bin, TrUserData) -> id(decode_msg_list_hosts_request(Bin, TrUserData), TrUserData);
decode_msg_2_doit(list_hosts_response, Bin, TrUserData) -> id(decode_msg_list_hosts_response(Bin, TrUserData), TrUserData);
decode_msg_2_doit(register_host_request, Bin, TrUserData) -> id(decode_msg_register_host_request(Bin, TrUserData), TrUserData);
decode_msg_2_doit(heartbeat_request, Bin, TrUserData) -> id(decode_msg_heartbeat_request(Bin, TrUserData), TrUserData);
decode_msg_2_doit(heartbeat_response, Bin, TrUserData) -> id(decode_msg_heartbeat_response(Bin, TrUserData), TrUserData);
decode_msg_2_doit(empty, Bin, TrUserData) -> id(decode_msg_empty(Bin, TrUserData), TrUserData).



decode_msg_create_bootstrap_token_request(Bin, TrUserData) -> dfp_read_field_def_create_bootstrap_token_request(Bin, 0, 0, 0, id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_create_bootstrap_token_request(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_create_bootstrap_token_request_expires_at(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_create_bootstrap_token_request(<<>>, 0, 0, _, F@_1, _) -> #{expires_at => F@_1};
dfp_read_field_def_create_bootstrap_token_request(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_create_bootstrap_token_request(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_create_bootstrap_token_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_create_bootstrap_token_request(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_create_bootstrap_token_request(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_create_bootstrap_token_request_expires_at(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_create_bootstrap_token_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_create_bootstrap_token_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_create_bootstrap_token_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_create_bootstrap_token_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_create_bootstrap_token_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_create_bootstrap_token_request(<<>>, 0, 0, _, F@_1, _) -> #{expires_at => F@_1}.

d_field_create_bootstrap_token_request_expires_at(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_create_bootstrap_token_request_expires_at(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_create_bootstrap_token_request_expires_at(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_create_bootstrap_token_request(RestF, 0, 0, F, NewFValue, TrUserData).

skip_varint_create_bootstrap_token_request(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_create_bootstrap_token_request(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_create_bootstrap_token_request(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_create_bootstrap_token_request(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_create_bootstrap_token_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_create_bootstrap_token_request(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_create_bootstrap_token_request(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_create_bootstrap_token_request(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_create_bootstrap_token_request(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_create_bootstrap_token_request(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_create_bootstrap_token_request(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_create_bootstrap_token_request(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_create_bootstrap_token_request(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_create_bootstrap_token_request(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_create_bootstrap_token_response(Bin, TrUserData) -> dfp_read_field_def_create_bootstrap_token_response(Bin, 0, 0, 0, id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_create_bootstrap_token_response(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_create_bootstrap_token_response_token(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_create_bootstrap_token_response(<<>>, 0, 0, _, F@_1, _) -> #{token => F@_1};
dfp_read_field_def_create_bootstrap_token_response(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_create_bootstrap_token_response(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_create_bootstrap_token_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_create_bootstrap_token_response(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_create_bootstrap_token_response(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_create_bootstrap_token_response_token(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_create_bootstrap_token_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_create_bootstrap_token_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_create_bootstrap_token_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_create_bootstrap_token_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_create_bootstrap_token_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_create_bootstrap_token_response(<<>>, 0, 0, _, F@_1, _) -> #{token => F@_1}.

d_field_create_bootstrap_token_response_token(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_create_bootstrap_token_response_token(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_create_bootstrap_token_response_token(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_create_bootstrap_token_response(RestF, 0, 0, F, NewFValue, TrUserData).

skip_varint_create_bootstrap_token_response(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_create_bootstrap_token_response(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_create_bootstrap_token_response(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_create_bootstrap_token_response(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_create_bootstrap_token_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_create_bootstrap_token_response(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_create_bootstrap_token_response(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_create_bootstrap_token_response(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_create_bootstrap_token_response(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_create_bootstrap_token_response(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_create_bootstrap_token_response(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_create_bootstrap_token_response(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_create_bootstrap_token_response(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_create_bootstrap_token_response(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_host(Bin, TrUserData) -> dfp_read_field_def_host(Bin, 0, 0, 0, id(<<>>, TrUserData), id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_host(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_host_name(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_host(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_host_address(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_host(<<>>, 0, 0, _, F@_1, F@_2, _) -> #{name => F@_1, address => F@_2};
dfp_read_field_def_host(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dg_read_field_def_host(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

dg_read_field_def_host(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 -> dg_read_field_def_host(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
dg_read_field_def_host(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_host_name(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        18 -> d_field_host_address(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_host(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                1 -> skip_64_host(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                2 -> skip_length_delimited_host(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                3 -> skip_group_host(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                5 -> skip_32_host(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
            end
    end;
dg_read_field_def_host(<<>>, 0, 0, _, F@_1, F@_2, _) -> #{name => F@_1, address => F@_2}.

d_field_host_name(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_host_name(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_host_name(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_host(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

d_field_host_address(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_host_address(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_host_address(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_host(RestF, 0, 0, F, F@_1, NewFValue, TrUserData).

skip_varint_host(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> skip_varint_host(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
skip_varint_host(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_host(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_length_delimited_host(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> skip_length_delimited_host(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
skip_length_delimited_host(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_host(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

skip_group_host(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_host(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

skip_32_host(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_host(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_64_host(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_host(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

decode_msg_list_hosts_request(Bin, TrUserData) -> dfp_read_field_def_list_hosts_request(Bin, 0, 0, 0, TrUserData).

dfp_read_field_def_list_hosts_request(<<>>, 0, 0, _, _) -> #{};
dfp_read_field_def_list_hosts_request(Other, Z1, Z2, F, TrUserData) -> dg_read_field_def_list_hosts_request(Other, Z1, Z2, F, TrUserData).

dg_read_field_def_list_hosts_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 32 - 7 -> dg_read_field_def_list_hosts_request(Rest, N + 7, X bsl N + Acc, F, TrUserData);
dg_read_field_def_list_hosts_request(<<0:1, X:7, Rest/binary>>, N, Acc, _, TrUserData) ->
    Key = X bsl N + Acc,
    case Key band 7 of
        0 -> skip_varint_list_hosts_request(Rest, 0, 0, Key bsr 3, TrUserData);
        1 -> skip_64_list_hosts_request(Rest, 0, 0, Key bsr 3, TrUserData);
        2 -> skip_length_delimited_list_hosts_request(Rest, 0, 0, Key bsr 3, TrUserData);
        3 -> skip_group_list_hosts_request(Rest, 0, 0, Key bsr 3, TrUserData);
        5 -> skip_32_list_hosts_request(Rest, 0, 0, Key bsr 3, TrUserData)
    end;
dg_read_field_def_list_hosts_request(<<>>, 0, 0, _, _) -> #{}.

skip_varint_list_hosts_request(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> skip_varint_list_hosts_request(Rest, Z1, Z2, F, TrUserData);
skip_varint_list_hosts_request(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_list_hosts_request(Rest, Z1, Z2, F, TrUserData).

skip_length_delimited_list_hosts_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 57 -> skip_length_delimited_list_hosts_request(Rest, N + 7, X bsl N + Acc, F, TrUserData);
skip_length_delimited_list_hosts_request(<<0:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_list_hosts_request(Rest2, 0, 0, F, TrUserData).

skip_group_list_hosts_request(Bin, _, Z2, FNum, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_list_hosts_request(Rest, 0, Z2, FNum, TrUserData).

skip_32_list_hosts_request(<<_:32, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_list_hosts_request(Rest, Z1, Z2, F, TrUserData).

skip_64_list_hosts_request(<<_:64, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_list_hosts_request(Rest, Z1, Z2, F, TrUserData).

decode_msg_list_hosts_response(Bin, TrUserData) -> dfp_read_field_def_list_hosts_response(Bin, 0, 0, 0, id([], TrUserData), TrUserData).

dfp_read_field_def_list_hosts_response(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_list_hosts_response_hosts(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_list_hosts_response(<<>>, 0, 0, _, R1, TrUserData) ->
    S1 = #{},
    if R1 == '$undef' -> S1;
       true -> S1#{hosts => lists_reverse(R1, TrUserData)}
    end;
dfp_read_field_def_list_hosts_response(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_list_hosts_response(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_list_hosts_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_list_hosts_response(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_list_hosts_response(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_list_hosts_response_hosts(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_list_hosts_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_list_hosts_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_list_hosts_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_list_hosts_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_list_hosts_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_list_hosts_response(<<>>, 0, 0, _, R1, TrUserData) ->
    S1 = #{},
    if R1 == '$undef' -> S1;
       true -> S1#{hosts => lists_reverse(R1, TrUserData)}
    end.

d_field_list_hosts_response_hosts(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_list_hosts_response_hosts(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_list_hosts_response_hosts(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_host(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_list_hosts_response(RestF, 0, 0, F, cons(NewFValue, Prev, TrUserData), TrUserData).

skip_varint_list_hosts_response(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_list_hosts_response(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_list_hosts_response(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_list_hosts_response(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_list_hosts_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_list_hosts_response(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_list_hosts_response(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_list_hosts_response(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_list_hosts_response(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_list_hosts_response(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_list_hosts_response(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_list_hosts_response(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_list_hosts_response(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_list_hosts_response(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_register_host_request(Bin, TrUserData) -> dfp_read_field_def_register_host_request(Bin, 0, 0, 0, id('$undef', TrUserData), id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_register_host_request(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_register_host_request_host(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_register_host_request(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_register_host_request_token(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_register_host_request(<<>>, 0, 0, _, F@_1, F@_2, _) ->
    S1 = #{token => F@_2},
    if F@_1 == '$undef' -> S1;
       true -> S1#{host => F@_1}
    end;
dfp_read_field_def_register_host_request(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dg_read_field_def_register_host_request(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

dg_read_field_def_register_host_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 -> dg_read_field_def_register_host_request(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
dg_read_field_def_register_host_request(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_register_host_request_host(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        18 -> d_field_register_host_request_token(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_register_host_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                1 -> skip_64_register_host_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                2 -> skip_length_delimited_register_host_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                3 -> skip_group_register_host_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                5 -> skip_32_register_host_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
            end
    end;
dg_read_field_def_register_host_request(<<>>, 0, 0, _, F@_1, F@_2, _) ->
    S1 = #{token => F@_2},
    if F@_1 == '$undef' -> S1;
       true -> S1#{host => F@_1}
    end.

d_field_register_host_request_host(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_register_host_request_host(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_register_host_request_host(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, F@_2, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_host(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_register_host_request(RestF,
                                             0,
                                             0,
                                             F,
                                             if Prev == '$undef' -> NewFValue;
                                                true -> merge_msg_host(Prev, NewFValue, TrUserData)
                                             end,
                                             F@_2,
                                             TrUserData).

d_field_register_host_request_token(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_register_host_request_token(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_register_host_request_token(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_register_host_request(RestF, 0, 0, F, F@_1, NewFValue, TrUserData).

skip_varint_register_host_request(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> skip_varint_register_host_request(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
skip_varint_register_host_request(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_register_host_request(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_length_delimited_register_host_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> skip_length_delimited_register_host_request(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
skip_length_delimited_register_host_request(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_register_host_request(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

skip_group_register_host_request(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_register_host_request(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

skip_32_register_host_request(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_register_host_request(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_64_register_host_request(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_register_host_request(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

decode_msg_heartbeat_request(Bin, TrUserData) -> dfp_read_field_def_heartbeat_request(Bin, 0, 0, 0, id('$undef', TrUserData), TrUserData).

dfp_read_field_def_heartbeat_request(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_heartbeat_request_host(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_heartbeat_request(<<>>, 0, 0, _, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{host => F@_1}
    end;
dfp_read_field_def_heartbeat_request(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_heartbeat_request(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_heartbeat_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_heartbeat_request(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_heartbeat_request(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_heartbeat_request_host(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_heartbeat_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_heartbeat_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_heartbeat_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_heartbeat_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_heartbeat_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_heartbeat_request(<<>>, 0, 0, _, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{host => F@_1}
    end.

d_field_heartbeat_request_host(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_heartbeat_request_host(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_heartbeat_request_host(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_host(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_heartbeat_request(RestF,
                                         0,
                                         0,
                                         F,
                                         if Prev == '$undef' -> NewFValue;
                                            true -> merge_msg_host(Prev, NewFValue, TrUserData)
                                         end,
                                         TrUserData).

skip_varint_heartbeat_request(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_heartbeat_request(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_heartbeat_request(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_heartbeat_request(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_heartbeat_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_heartbeat_request(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_heartbeat_request(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_heartbeat_request(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_heartbeat_request(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_heartbeat_request(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_heartbeat_request(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_heartbeat_request(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_heartbeat_request(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_heartbeat_request(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_heartbeat_response(Bin, TrUserData) -> dfp_read_field_def_heartbeat_response(Bin, 0, 0, 0, TrUserData).

dfp_read_field_def_heartbeat_response(<<>>, 0, 0, _, _) -> #{};
dfp_read_field_def_heartbeat_response(Other, Z1, Z2, F, TrUserData) -> dg_read_field_def_heartbeat_response(Other, Z1, Z2, F, TrUserData).

dg_read_field_def_heartbeat_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 32 - 7 -> dg_read_field_def_heartbeat_response(Rest, N + 7, X bsl N + Acc, F, TrUserData);
dg_read_field_def_heartbeat_response(<<0:1, X:7, Rest/binary>>, N, Acc, _, TrUserData) ->
    Key = X bsl N + Acc,
    case Key band 7 of
        0 -> skip_varint_heartbeat_response(Rest, 0, 0, Key bsr 3, TrUserData);
        1 -> skip_64_heartbeat_response(Rest, 0, 0, Key bsr 3, TrUserData);
        2 -> skip_length_delimited_heartbeat_response(Rest, 0, 0, Key bsr 3, TrUserData);
        3 -> skip_group_heartbeat_response(Rest, 0, 0, Key bsr 3, TrUserData);
        5 -> skip_32_heartbeat_response(Rest, 0, 0, Key bsr 3, TrUserData)
    end;
dg_read_field_def_heartbeat_response(<<>>, 0, 0, _, _) -> #{}.

skip_varint_heartbeat_response(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> skip_varint_heartbeat_response(Rest, Z1, Z2, F, TrUserData);
skip_varint_heartbeat_response(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_heartbeat_response(Rest, Z1, Z2, F, TrUserData).

skip_length_delimited_heartbeat_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 57 -> skip_length_delimited_heartbeat_response(Rest, N + 7, X bsl N + Acc, F, TrUserData);
skip_length_delimited_heartbeat_response(<<0:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_heartbeat_response(Rest2, 0, 0, F, TrUserData).

skip_group_heartbeat_response(Bin, _, Z2, FNum, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_heartbeat_response(Rest, 0, Z2, FNum, TrUserData).

skip_32_heartbeat_response(<<_:32, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_heartbeat_response(Rest, Z1, Z2, F, TrUserData).

skip_64_heartbeat_response(<<_:64, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_heartbeat_response(Rest, Z1, Z2, F, TrUserData).

decode_msg_empty(Bin, TrUserData) -> dfp_read_field_def_empty(Bin, 0, 0, 0, TrUserData).

dfp_read_field_def_empty(<<>>, 0, 0, _, _) -> #{};
dfp_read_field_def_empty(Other, Z1, Z2, F, TrUserData) -> dg_read_field_def_empty(Other, Z1, Z2, F, TrUserData).

dg_read_field_def_empty(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 32 - 7 -> dg_read_field_def_empty(Rest, N + 7, X bsl N + Acc, F, TrUserData);
dg_read_field_def_empty(<<0:1, X:7, Rest/binary>>, N, Acc, _, TrUserData) ->
    Key = X bsl N + Acc,
    case Key band 7 of
        0 -> skip_varint_empty(Rest, 0, 0, Key bsr 3, TrUserData);
        1 -> skip_64_empty(Rest, 0, 0, Key bsr 3, TrUserData);
        2 -> skip_length_delimited_empty(Rest, 0, 0, Key bsr 3, TrUserData);
        3 -> skip_group_empty(Rest, 0, 0, Key bsr 3, TrUserData);
        5 -> skip_32_empty(Rest, 0, 0, Key bsr 3, TrUserData)
    end;
dg_read_field_def_empty(<<>>, 0, 0, _, _) -> #{}.

skip_varint_empty(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> skip_varint_empty(Rest, Z1, Z2, F, TrUserData);
skip_varint_empty(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_empty(Rest, Z1, Z2, F, TrUserData).

skip_length_delimited_empty(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 57 -> skip_length_delimited_empty(Rest, N + 7, X bsl N + Acc, F, TrUserData);
skip_length_delimited_empty(<<0:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_empty(Rest2, 0, 0, F, TrUserData).

skip_group_empty(Bin, _, Z2, FNum, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_empty(Rest, 0, Z2, FNum, TrUserData).

skip_32_empty(<<_:32, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_empty(Rest, Z1, Z2, F, TrUserData).

skip_64_empty(<<_:64, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_empty(Rest, Z1, Z2, F, TrUserData).

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        create_bootstrap_token_request -> merge_msg_create_bootstrap_token_request(Prev, New, TrUserData);
        create_bootstrap_token_response -> merge_msg_create_bootstrap_token_response(Prev, New, TrUserData);
        host -> merge_msg_host(Prev, New, TrUserData);
        list_hosts_request -> merge_msg_list_hosts_request(Prev, New, TrUserData);
        list_hosts_response -> merge_msg_list_hosts_response(Prev, New, TrUserData);
        register_host_request -> merge_msg_register_host_request(Prev, New, TrUserData);
        heartbeat_request -> merge_msg_heartbeat_request(Prev, New, TrUserData);
        heartbeat_response -> merge_msg_heartbeat_response(Prev, New, TrUserData);
        empty -> merge_msg_empty(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_create_bootstrap_token_request/3}).
merge_msg_create_bootstrap_token_request(PMsg, NMsg, _) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {_, #{expires_at := NFexpires_at}} -> S1#{expires_at => NFexpires_at};
        {#{expires_at := PFexpires_at}, _} -> S1#{expires_at => PFexpires_at};
        _ -> S1
    end.

-compile({nowarn_unused_function,merge_msg_create_bootstrap_token_response/3}).
merge_msg_create_bootstrap_token_response(PMsg, NMsg, _) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {_, #{token := NFtoken}} -> S1#{token => NFtoken};
        {#{token := PFtoken}, _} -> S1#{token => PFtoken};
        _ -> S1
    end.

-compile({nowarn_unused_function,merge_msg_host/3}).
merge_msg_host(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{name := NFname}} -> S1#{name => NFname};
             {#{name := PFname}, _} -> S1#{name => PFname};
             _ -> S1
         end,
    case {PMsg, NMsg} of
        {_, #{address := NFaddress}} -> S2#{address => NFaddress};
        {#{address := PFaddress}, _} -> S2#{address => PFaddress};
        _ -> S2
    end.

-compile({nowarn_unused_function,merge_msg_list_hosts_request/3}).
merge_msg_list_hosts_request(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,merge_msg_list_hosts_response/3}).
merge_msg_list_hosts_response(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {#{hosts := PFhosts}, #{hosts := NFhosts}} -> S1#{hosts => 'erlang_++'(PFhosts, NFhosts, TrUserData)};
        {_, #{hosts := NFhosts}} -> S1#{hosts => NFhosts};
        {#{hosts := PFhosts}, _} -> S1#{hosts => PFhosts};
        {_, _} -> S1
    end.

-compile({nowarn_unused_function,merge_msg_register_host_request/3}).
merge_msg_register_host_request(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {#{host := PFhost}, #{host := NFhost}} -> S1#{host => merge_msg_host(PFhost, NFhost, TrUserData)};
             {_, #{host := NFhost}} -> S1#{host => NFhost};
             {#{host := PFhost}, _} -> S1#{host => PFhost};
             {_, _} -> S1
         end,
    case {PMsg, NMsg} of
        {_, #{token := NFtoken}} -> S2#{token => NFtoken};
        {#{token := PFtoken}, _} -> S2#{token => PFtoken};
        _ -> S2
    end.

-compile({nowarn_unused_function,merge_msg_heartbeat_request/3}).
merge_msg_heartbeat_request(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {#{host := PFhost}, #{host := NFhost}} -> S1#{host => merge_msg_host(PFhost, NFhost, TrUserData)};
        {_, #{host := NFhost}} -> S1#{host => NFhost};
        {#{host := PFhost}, _} -> S1#{host => PFhost};
        {_, _} -> S1
    end.

-compile({nowarn_unused_function,merge_msg_heartbeat_response/3}).
merge_msg_heartbeat_response(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,merge_msg_empty/3}).
merge_msg_empty(_Prev, New, _TrUserData) -> New.


verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        create_bootstrap_token_request -> v_msg_create_bootstrap_token_request(Msg, [MsgName], TrUserData);
        create_bootstrap_token_response -> v_msg_create_bootstrap_token_response(Msg, [MsgName], TrUserData);
        host -> v_msg_host(Msg, [MsgName], TrUserData);
        list_hosts_request -> v_msg_list_hosts_request(Msg, [MsgName], TrUserData);
        list_hosts_response -> v_msg_list_hosts_response(Msg, [MsgName], TrUserData);
        register_host_request -> v_msg_register_host_request(Msg, [MsgName], TrUserData);
        heartbeat_request -> v_msg_heartbeat_request(Msg, [MsgName], TrUserData);
        heartbeat_response -> v_msg_heartbeat_response(Msg, [MsgName], TrUserData);
        empty -> v_msg_empty(Msg, [MsgName], TrUserData);
        _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_create_bootstrap_token_request/3}).
-dialyzer({nowarn_function,v_msg_create_bootstrap_token_request/3}).
v_msg_create_bootstrap_token_request(#{} = M, Path, TrUserData) ->
    case M of
        #{expires_at := F1} -> v_type_string(F1, [expires_at | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (expires_at) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_create_bootstrap_token_request(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), create_bootstrap_token_request}, M, Path);
v_msg_create_bootstrap_token_request(X, Path, _TrUserData) -> mk_type_error({expected_msg, create_bootstrap_token_request}, X, Path).

-compile({nowarn_unused_function,v_msg_create_bootstrap_token_response/3}).
-dialyzer({nowarn_function,v_msg_create_bootstrap_token_response/3}).
v_msg_create_bootstrap_token_response(#{} = M, Path, TrUserData) ->
    case M of
        #{token := F1} -> v_type_string(F1, [token | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (token) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_create_bootstrap_token_response(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), create_bootstrap_token_response}, M, Path);
v_msg_create_bootstrap_token_response(X, Path, _TrUserData) -> mk_type_error({expected_msg, create_bootstrap_token_response}, X, Path).

-compile({nowarn_unused_function,v_msg_host/3}).
-dialyzer({nowarn_function,v_msg_host/3}).
v_msg_host(#{} = M, Path, TrUserData) ->
    case M of
        #{name := F1} -> v_type_string(F1, [name | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{address := F2} -> v_type_string(F2, [address | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (name) -> ok;
                      (address) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_host(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), host}, M, Path);
v_msg_host(X, Path, _TrUserData) -> mk_type_error({expected_msg, host}, X, Path).

-compile({nowarn_unused_function,v_msg_list_hosts_request/3}).
-dialyzer({nowarn_function,v_msg_list_hosts_request/3}).
v_msg_list_hosts_request(#{} = M, Path, _) ->
    lists:foreach(fun (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path) end, maps:keys(M)),
    ok;
v_msg_list_hosts_request(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), list_hosts_request}, M, Path);
v_msg_list_hosts_request(X, Path, _TrUserData) -> mk_type_error({expected_msg, list_hosts_request}, X, Path).

-compile({nowarn_unused_function,v_msg_list_hosts_response/3}).
-dialyzer({nowarn_function,v_msg_list_hosts_response/3}).
v_msg_list_hosts_response(#{} = M, Path, TrUserData) ->
    case M of
        #{hosts := F1} ->
            if is_list(F1) ->
                   _ = [v_msg_host(Elem, [hosts | Path], TrUserData) || Elem <- F1],
                   ok;
               true -> mk_type_error({invalid_list_of, {msg, host}}, F1, [hosts | Path])
            end;
        _ -> ok
    end,
    lists:foreach(fun (hosts) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_list_hosts_response(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), list_hosts_response}, M, Path);
v_msg_list_hosts_response(X, Path, _TrUserData) -> mk_type_error({expected_msg, list_hosts_response}, X, Path).

-compile({nowarn_unused_function,v_msg_register_host_request/3}).
-dialyzer({nowarn_function,v_msg_register_host_request/3}).
v_msg_register_host_request(#{} = M, Path, TrUserData) ->
    case M of
        #{host := F1} -> v_msg_host(F1, [host | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{token := F2} -> v_type_string(F2, [token | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (host) -> ok;
                      (token) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_register_host_request(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), register_host_request}, M, Path);
v_msg_register_host_request(X, Path, _TrUserData) -> mk_type_error({expected_msg, register_host_request}, X, Path).

-compile({nowarn_unused_function,v_msg_heartbeat_request/3}).
-dialyzer({nowarn_function,v_msg_heartbeat_request/3}).
v_msg_heartbeat_request(#{} = M, Path, TrUserData) ->
    case M of
        #{host := F1} -> v_msg_host(F1, [host | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (host) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_heartbeat_request(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), heartbeat_request}, M, Path);
v_msg_heartbeat_request(X, Path, _TrUserData) -> mk_type_error({expected_msg, heartbeat_request}, X, Path).

-compile({nowarn_unused_function,v_msg_heartbeat_response/3}).
-dialyzer({nowarn_function,v_msg_heartbeat_response/3}).
v_msg_heartbeat_response(#{} = M, Path, _) ->
    lists:foreach(fun (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path) end, maps:keys(M)),
    ok;
v_msg_heartbeat_response(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), heartbeat_response}, M, Path);
v_msg_heartbeat_response(X, Path, _TrUserData) -> mk_type_error({expected_msg, heartbeat_response}, X, Path).

-compile({nowarn_unused_function,v_msg_empty/3}).
-dialyzer({nowarn_function,v_msg_empty/3}).
v_msg_empty(#{} = M, Path, _) ->
    lists:foreach(fun (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path) end, maps:keys(M)),
    ok;
v_msg_empty(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), empty}, M, Path);
v_msg_empty(X, Path, _TrUserData) -> mk_type_error({expected_msg, empty}, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
        B when is_binary(B) -> ok;
        {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
        error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) -> mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR)))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() ->
    [{{msg, create_bootstrap_token_request}, [#{name => expires_at, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []}]},
     {{msg, create_bootstrap_token_response}, [#{name => token, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []}]},
     {{msg, host}, [#{name => name, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []}, #{name => address, fnum => 2, rnum => 3, type => string, occurrence => optional, opts => []}]},
     {{msg, list_hosts_request}, []},
     {{msg, list_hosts_response}, [#{name => hosts, fnum => 1, rnum => 2, type => {msg, host}, occurrence => repeated, opts => []}]},
     {{msg, register_host_request}, [#{name => host, fnum => 1, rnum => 2, type => {msg, host}, occurrence => optional, opts => []}, #{name => token, fnum => 2, rnum => 3, type => string, occurrence => optional, opts => []}]},
     {{msg, heartbeat_request}, [#{name => host, fnum => 1, rnum => 2, type => {msg, host}, occurrence => optional, opts => []}]},
     {{msg, heartbeat_response}, []},
     {{msg, empty}, []}].


get_msg_names() -> [create_bootstrap_token_request, create_bootstrap_token_response, host, list_hosts_request, list_hosts_response, register_host_request, heartbeat_request, heartbeat_response, empty].


get_group_names() -> [].


get_msg_or_group_names() -> [create_bootstrap_token_request, create_bootstrap_token_response, host, list_hosts_request, list_hosts_response, register_host_request, heartbeat_request, heartbeat_response, empty].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
        Fs when is_list(Fs) -> Fs;
        error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) -> erlang:error({no_such_enum, EnumName}).


find_msg_def(create_bootstrap_token_request) -> [#{name => expires_at, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []}];
find_msg_def(create_bootstrap_token_response) -> [#{name => token, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []}];
find_msg_def(host) -> [#{name => name, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []}, #{name => address, fnum => 2, rnum => 3, type => string, occurrence => optional, opts => []}];
find_msg_def(list_hosts_request) -> [];
find_msg_def(list_hosts_response) -> [#{name => hosts, fnum => 1, rnum => 2, type => {msg, host}, occurrence => repeated, opts => []}];
find_msg_def(register_host_request) -> [#{name => host, fnum => 1, rnum => 2, type => {msg, host}, occurrence => optional, opts => []}, #{name => token, fnum => 2, rnum => 3, type => string, occurrence => optional, opts => []}];
find_msg_def(heartbeat_request) -> [#{name => host, fnum => 1, rnum => 2, type => {msg, host}, occurrence => optional, opts => []}];
find_msg_def(heartbeat_response) -> [];
find_msg_def(empty) -> [];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) -> erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) -> erlang:error({no_enum_defs, E, V}).



get_service_names() -> ['HostService'].


get_service_def('HostService') ->
    {{service, 'HostService'},
     [#{name => 'CreateBootstrapToken', input => create_bootstrap_token_request, output => create_bootstrap_token_response, input_stream => false, output_stream => false, opts => []},
      #{name => 'GetHost', input => host, output => host, input_stream => false, output_stream => false, opts => []},
      #{name => 'ListHosts', input => list_hosts_request, output => list_hosts_response, input_stream => false, output_stream => false, opts => []},
      #{name => 'Register', input => register_host_request, output => host, input_stream => false, output_stream => false, opts => []},
      #{name => 'Deregister', input => host, output => empty, input_stream => false, output_stream => false, opts => []},
      #{name => 'Heartbeat', input => heartbeat_request, output => heartbeat_response, input_stream => false, output_stream => false, opts => []}]};
get_service_def(_) -> error.


get_rpc_names('HostService') -> ['CreateBootstrapToken', 'GetHost', 'ListHosts', 'Register', 'Deregister', 'Heartbeat'];
get_rpc_names(_) -> error.


find_rpc_def('HostService', RpcName) -> find_rpc_def_HostService(RpcName);
find_rpc_def(_, _) -> error.


find_rpc_def_HostService('CreateBootstrapToken') -> #{name => 'CreateBootstrapToken', input => create_bootstrap_token_request, output => create_bootstrap_token_response, input_stream => false, output_stream => false, opts => []};
find_rpc_def_HostService('GetHost') -> #{name => 'GetHost', input => host, output => host, input_stream => false, output_stream => false, opts => []};
find_rpc_def_HostService('ListHosts') -> #{name => 'ListHosts', input => list_hosts_request, output => list_hosts_response, input_stream => false, output_stream => false, opts => []};
find_rpc_def_HostService('Register') -> #{name => 'Register', input => register_host_request, output => host, input_stream => false, output_stream => false, opts => []};
find_rpc_def_HostService('Deregister') -> #{name => 'Deregister', input => host, output => empty, input_stream => false, output_stream => false, opts => []};
find_rpc_def_HostService('Heartbeat') -> #{name => 'Heartbeat', input => heartbeat_request, output => heartbeat_response, input_stream => false, output_stream => false, opts => []};
find_rpc_def_HostService(_) -> error.


fetch_rpc_def(ServiceName, RpcName) ->
    case find_rpc_def(ServiceName, RpcName) of
        Def when is_map(Def) -> Def;
        error -> erlang:error({no_such_rpc, ServiceName, RpcName})
    end.


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
fqbin_to_service_name(<<"HostService">>) -> 'HostService';
fqbin_to_service_name(X) -> error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
service_name_to_fqbin('HostService') -> <<"HostService">>;
service_name_to_fqbin(X) -> error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
fqbins_to_service_and_rpc_name(<<"HostService">>, <<"CreateBootstrapToken">>) -> {'HostService', 'CreateBootstrapToken'};
fqbins_to_service_and_rpc_name(<<"HostService">>, <<"GetHost">>) -> {'HostService', 'GetHost'};
fqbins_to_service_and_rpc_name(<<"HostService">>, <<"ListHosts">>) -> {'HostService', 'ListHosts'};
fqbins_to_service_and_rpc_name(<<"HostService">>, <<"Register">>) -> {'HostService', 'Register'};
fqbins_to_service_and_rpc_name(<<"HostService">>, <<"Deregister">>) -> {'HostService', 'Deregister'};
fqbins_to_service_and_rpc_name(<<"HostService">>, <<"Heartbeat">>) -> {'HostService', 'Heartbeat'};
fqbins_to_service_and_rpc_name(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
service_and_rpc_name_to_fqbins('HostService', 'CreateBootstrapToken') -> {<<"HostService">>, <<"CreateBootstrapToken">>};
service_and_rpc_name_to_fqbins('HostService', 'GetHost') -> {<<"HostService">>, <<"GetHost">>};
service_and_rpc_name_to_fqbins('HostService', 'ListHosts') -> {<<"HostService">>, <<"ListHosts">>};
service_and_rpc_name_to_fqbins('HostService', 'Register') -> {<<"HostService">>, <<"Register">>};
service_and_rpc_name_to_fqbins('HostService', 'Deregister') -> {<<"HostService">>, <<"Deregister">>};
service_and_rpc_name_to_fqbins('HostService', 'Heartbeat') -> {<<"HostService">>, <<"Heartbeat">>};
service_and_rpc_name_to_fqbins(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"CreateBootstrapTokenRequest">>) -> create_bootstrap_token_request;
fqbin_to_msg_name(<<"CreateBootstrapTokenResponse">>) -> create_bootstrap_token_response;
fqbin_to_msg_name(<<"Host">>) -> host;
fqbin_to_msg_name(<<"ListHostsRequest">>) -> list_hosts_request;
fqbin_to_msg_name(<<"ListHostsResponse">>) -> list_hosts_response;
fqbin_to_msg_name(<<"RegisterHostRequest">>) -> register_host_request;
fqbin_to_msg_name(<<"HeartbeatRequest">>) -> heartbeat_request;
fqbin_to_msg_name(<<"HeartbeatResponse">>) -> heartbeat_response;
fqbin_to_msg_name(<<"google.protobuf.Empty">>) -> empty;
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin(create_bootstrap_token_request) -> <<"CreateBootstrapTokenRequest">>;
msg_name_to_fqbin(create_bootstrap_token_response) -> <<"CreateBootstrapTokenResponse">>;
msg_name_to_fqbin(host) -> <<"Host">>;
msg_name_to_fqbin(list_hosts_request) -> <<"ListHostsRequest">>;
msg_name_to_fqbin(list_hosts_response) -> <<"ListHostsResponse">>;
msg_name_to_fqbin(register_host_request) -> <<"RegisterHostRequest">>;
msg_name_to_fqbin(heartbeat_request) -> <<"HeartbeatRequest">>;
msg_name_to_fqbin(heartbeat_response) -> <<"HeartbeatResponse">>;
msg_name_to_fqbin(empty) -> <<"google.protobuf.Empty">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec fqbin_to_enum_name(_) -> no_return().
fqbin_to_enum_name(E) -> error({gpb_error, {badenum, E}}).


-spec enum_name_to_fqbin(_) -> no_return().
enum_name_to_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_package_name() -> 'google.protobuf'.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> true.


source_basename() -> "host.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() -> ["host.proto", "empty.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["host", "empty"].


get_msg_containment("host") -> [create_bootstrap_token_request, create_bootstrap_token_response, heartbeat_request, heartbeat_response, host, list_hosts_request, list_hosts_response, register_host_request];
get_msg_containment("empty") -> [empty];
get_msg_containment(P) -> error({gpb_error, {badproto, P}}).


get_pkg_containment("host") -> undefined;
get_pkg_containment("empty") -> 'google.protobuf';
get_pkg_containment(P) -> error({gpb_error, {badproto, P}}).


get_service_containment("host") -> ['HostService'];
get_service_containment("empty") -> [];
get_service_containment(P) -> error({gpb_error, {badproto, P}}).


get_rpc_containment("host") -> [{'HostService', 'CreateBootstrapToken'}, {'HostService', 'GetHost'}, {'HostService', 'ListHosts'}, {'HostService', 'Register'}, {'HostService', 'Deregister'}, {'HostService', 'Heartbeat'}];
get_rpc_containment("empty") -> [];
get_rpc_containment(P) -> error({gpb_error, {badproto, P}}).


get_enum_containment("host") -> [];
get_enum_containment("empty") -> [];
get_enum_containment(P) -> error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"RegisterHostRequest">>) -> "host";
get_proto_by_msg_name_as_fqbin(<<"ListHostsRequest">>) -> "host";
get_proto_by_msg_name_as_fqbin(<<"Host">>) -> "host";
get_proto_by_msg_name_as_fqbin(<<"HeartbeatRequest">>) -> "host";
get_proto_by_msg_name_as_fqbin(<<"CreateBootstrapTokenRequest">>) -> "host";
get_proto_by_msg_name_as_fqbin(<<"ListHostsResponse">>) -> "host";
get_proto_by_msg_name_as_fqbin(<<"HeartbeatResponse">>) -> "host";
get_proto_by_msg_name_as_fqbin(<<"CreateBootstrapTokenResponse">>) -> "host";
get_proto_by_msg_name_as_fqbin(<<"google.protobuf.Empty">>) -> "empty";
get_proto_by_msg_name_as_fqbin(E) -> error({gpb_error, {badmsg, E}}).


get_proto_by_service_name_as_fqbin(<<"HostService">>) -> "host";
get_proto_by_service_name_as_fqbin(E) -> error({gpb_error, {badservice, E}}).


-spec get_proto_by_enum_name_as_fqbin(_) -> no_return().
get_proto_by_enum_name_as_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_protos_by_pkg_name_as_fqbin(<<"google.protobuf">>) -> ["empty"];
get_protos_by_pkg_name_as_fqbin(E) -> error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.19.8".

gpb_version_as_list() ->
    [4,19,8].

gpb_version_source() ->
    "file".
