version: "3.3"
services:
  web:
    image: restvirt:latest
    command:
      - -b
      - :8093
      - --ssl-cert
      - /etc/restvirt/cert.pem
      - --ssl-priv
      - /etc/restvirt/privkey.pem
      - --htpasswd
      - /etc/restvirt/htpasswd
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    volumes:
      - "/etc/restvirt:/etc/restvirt"
      - "/data/restvirt:/data/restvirt"
      - "/var/run/libvirt:/var/run/libvirt"
