name: minivirt # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: 'git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  controller:
    command: bin/restvirt-controller
    daemon: simple
    plugs:
      - network
      - network-bind
  unbound:
    command: bin/unbound-wrapper
    daemon: simple
    after:
      - controller
    plugs:
      - network
      - network-bind
  bird:
    command: bin/bird-wrapper
    daemon: simple
    before:
      - daemon
    plugs:
      - network
      - network-bind
      - network-control
  birdc:
    command: bin/birdc-wrapper
  register:
    command: bin/restvirt-register
    plugs:
      - network
      - network-bind
  deregister:
    command: bin/restvirt-deregister
    plugs:
      - network
      - network-bind
  daemon:
    command: bin/restvirt-daemon
    daemon: simple
    after:
      - controller
    restart-condition: always
    restart-delay: 2s
    plugs:
      - libvirt
      - network
      - network-bind
      - network-control
      - firewall-control

parts:
  wrapper:
    plugin: dump
    source: snap/local/
    stage-packages:
      - gettext-base
  minivirt:
    # See 'snapcraft plugins'
    plugin: python
    source: ./
    build-packages:
      - git
      - libvirt-dev
      - pkg-config
    stage-packages:
      - libvirt0
      - libbrotli1  # kill me please
      - libnftables1
      - unbound
      - bird2
