name: Build
on:
  push:
    branches-ignore:
      - main
jobs:
  restvirt:
    name: Restvirt
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Python 3.9.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install -y libvirt-dev
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Lint
        run: |
          black --check --diff --color ./
          isort --check --diff --color ./
      - name: Test
        run: |
          docker build --target test -t restvirt-tests .
          tmp_dir=$(mktemp -d)
          docker run --rm --cap-add=NET_ADMIN -t -v "${tmp_dir}":/data/restvirt/images restvirt-tests
      - name: Build
        run: docker build -t restvirt .
