name: Build
on:
  push:
    branches-ignore:
      - main
jobs:
  restvirt:
    name: Restvirt
    runs-on: self-hosted
    steps:
      - name: Set up Python 3.10.6
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libvirt-dev
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Lint
        run: |
          black --check --diff --color ./
          isort --check --diff --color ./
      - name: Test
        run: |
          tmp_dir=$(mktemp -d)
          chmod -R 0711 "${tmp_dir}"
          sudo iptables -P FORWARD ACCEPT
          sudo ${{ steps.python.outputs.python-path }} -m pytest
      - name: Build Snap
        uses: snapcore/action-build@v1
        id: snapcraft
#      - name: Build
#        run: |
#          docker build --target test -t restvirt-tests .
#          docker build -t restvirt .
#      - name: Test
#        run: |
#          tmp_dir=$(mktemp -d)
#          chmod -R 0711 "${tmp_dir}"
#          iptables -P FORWARD ACCEPT
#          docker run --rm --cap-add=NET_ADMIN --network host -t -v /var/run/libvirt:/var/run/libvirt -v "${tmp_dir}":/data/restvirt/images restvirt-tests --pool-dir "${tmp_dir}"
