name: Deploy
on:
  push:
    tags:
      - v*
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
