name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: verbit
          password: ${{ secrets.GHCR_PAT }}
      - name: Deploy image
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          DATE=$(date +%Y%m%d%H%M%S)
          IMAGE_VERSION=ci-${SHA_SHORT}-${DATE}
          docker build -t restvirt:${IMAGE_VERSION} .
          docker tag restvirt:${IMAGE_VERSION} ghcr.io/verbit/restvirt:${IMAGE_VERSION}
          docker push ghcr.io/verbit/restvirt:${IMAGE_VERSION}
