name: Build
on:
  push:
    branches-ignore:
      - main
jobs:
  virtuerl:
    name: virtuerl
    runs-on: self-hosted
    defaults:
      run:
        working-directory: virtuerl
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y rebar3 g++ tree
      - name: Test
        run: |
          sudo rebar3 ct
      - name: Create tar
        run: |
          sudo rebar3 tar
          sudo find _build/ -name '*.tar.gz' -exec hack/repack {} \;
