name: Build
on:
  push:
    branches-ignore:
      - main
jobs:
  virtuerl:
    name: virtuerl
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y rebar3 g++ tree nftables ovmf swtpm make golang
      - name: Enable IP forwarding
        run: |
          sudo tee /etc/sysctl.d/99-local.conf << EOF
          net.ipv4.ip_forward=1
          net.ipv6.conf.all.forwarding=1
          EOF
          sudo service procps restart
      - name: Setup virtuerl_helper
        run: |
          make -C helper
          mkdir -p ~/.local/bin
          ln -s "${PWD}/helper/virtuerl_helper" ~/.local/bin/virtuerl_helper
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Test
        run: |
          rebar3 efmt --check
          rebar3 ct
      - name: Create tar
        run: |
          rebar3 tar
          find _build/ -name '*.tar.gz' -exec hack/repack {} \;
